const deleteStudentBook =async (req,res)=>{
    try{

    }
    catch(error){
        console.log("error in delete studentbookobject");
        res.send(error.message)
    }

}